### ISSUE TITLE
Hello, my name is Mingming  Huang, Do you have a version of iperf2?

### ISSUE THREAD

**Issue by Hmm466** [yeahdongcn/iperf-iOS#4]
Hello, my name is Mingming  Huang, Do you have a version of iperf2?
My Android  version is Iperf2.You  project version is Iperf3.

**Comment by vardhanvishnu67** [comment]
No im also using iper3.

**Comment by Hmm466** [comment]
I was a Android developer and I could only write simple iOS applications. Do you have a iperf2 case?
thanks

**Comment by yeahdongcn** [comment]
I'm afraid I don't have one. This would be simple you can get it done by yourself.

**Comment by Hmm466** [comment]
Thanks for your answer. I just didn't find iperf2's library file
